version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: marketplace_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0Qwerty12$&
      POSTGRES_DB: marketplace
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: marketplace_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:
